---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '[%(asctime)s - %(filename)s - %(levelname)s] %(message)s'
  normal:
    format: "[%(asctime)s - %(name)s -  %(filename)s - %(levelname)s] : %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  server_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: normal
    filename: server.log
    interval: 1
    backupCount: 15
    encoding: utf8
    when: midnight

  cron_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: normal
    filename: cron.log
    interval: 1
    backupCount: 15
    encoding: utf8
    when: midnight

  default_handler:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: normal
    filename: default.log
    interval: 1
    backupCount: 15
    encoding: utf8
    when: midnight


#root:not found logger,use root
root:
  level: INFO
  handlers: [console,default_handler]

loggers:
  server:
    level: DEBUG
    handlers: [server_handler,console]
    propagate: no

  cron:
    level: DEBUG
    handlers: [cron_handler]
    propagate: no